// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using Rg.ClientApp.Models;

namespace Rg.ClientApp.Models
{
    public static partial class AlbumSummaryCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<AlbumSummary> DeserializeJson(JToken inputObject)
        {
            IList<AlbumSummary> deserializedObject = new List<AlbumSummary>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                AlbumSummary albumSummary = new AlbumSummary();
                albumSummary.DeserializeJson(iListValue);
                deserializedObject.Add(albumSummary);
            }
            return deserializedObject;
        }
    }
}
