// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Rg.ClientApp.Models
{
    public partial class CreateTimelineEntry
    {
        private IList<int?> _mediaIds;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<int?> MediaIds
        {
            get { return this._mediaIds; }
            set { this._mediaIds = value; }
        }
        
        private string _message;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Message
        {
            get { return this._message; }
            set { this._message = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CreateTimelineEntry class.
        /// </summary>
        public CreateTimelineEntry()
        {
            this.MediaIds = new LazyList<int?>();
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type CreateTimelineEntry
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray mediaIdsSequence = null;
            if (this.MediaIds != null)
            {
                if (this.MediaIds is ILazyCollection<int> == false || ((ILazyCollection<int>)this.MediaIds).IsInitialized)
                {
                    mediaIdsSequence = new JArray();
                    outputObject["MediaIds"] = mediaIdsSequence;
                    foreach (int? mediaIdsItem in this.MediaIds)
                    {
                        if (mediaIdsItem != null)
                        {
                            mediaIdsSequence.Add(mediaIdsItem.Value);
                        }
                    }
                }
            }
            if (this.Message != null)
            {
                outputObject["Message"] = this.Message;
            }
            return outputObject;
        }
    }
}
