// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Rg.ClientApp.Models
{
    public partial class LikeRequest
    {
        private string _likeKind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string LikeKind
        {
            get { return this._likeKind; }
            set { this._likeKind = value; }
        }
        
        private bool? _set;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Set
        {
            get { return this._set; }
            set { this._set = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the LikeRequest class.
        /// </summary>
        public LikeRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type LikeRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.LikeKind != null)
            {
                outputObject["LikeKind"] = this.LikeKind;
            }
            if (this.Set != null)
            {
                outputObject["Set"] = this.Set.Value;
            }
            return outputObject;
        }
    }
}
