// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Rg.ClientApp.Models
{
    public partial class NotificationRegistration
    {
        private string _handle;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Handle
        {
            get { return this._handle; }
            set { this._handle = value; }
        }
        
        private string _platform;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Platform
        {
            get { return this._platform; }
            set { this._platform = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the NotificationRegistration class.
        /// </summary>
        public NotificationRegistration()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type NotificationRegistration
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Handle != null)
            {
                outputObject["Handle"] = this.Handle;
            }
            if (this.Platform != null)
            {
                outputObject["Platform"] = this.Platform;
            }
            return outputObject;
        }
    }
}
