// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Rg.ClientApp.Models
{
    public partial class OptionSettings
    {
        private bool? _isEnabled;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsEnabled
        {
            get { return this._isEnabled; }
            set { this._isEnabled = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the OptionSettings class.
        /// </summary>
        public OptionSettings()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type OptionSettings
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.IsEnabled != null)
            {
                outputObject["IsEnabled"] = this.IsEnabled.Value;
            }
            return outputObject;
        }
    }
}
