// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using Rg.ClientApp.Models;

namespace Rg.ClientApp.Models
{
    public partial class SearchResults
    {
        private IList<SearchResult> _albumMatches;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<SearchResult> AlbumMatches
        {
            get { return this._albumMatches; }
            set { this._albumMatches = value; }
        }
        
        private IList<SearchResult> _mediaMatches;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<SearchResult> MediaMatches
        {
            get { return this._mediaMatches; }
            set { this._mediaMatches = value; }
        }
        
        private IList<SearchResult> _timelineMatches;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<SearchResult> TimelineMatches
        {
            get { return this._timelineMatches; }
            set { this._timelineMatches = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SearchResults class.
        /// </summary>
        public SearchResults()
        {
            this.AlbumMatches = new LazyList<SearchResult>();
            this.MediaMatches = new LazyList<SearchResult>();
            this.TimelineMatches = new LazyList<SearchResult>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken albumMatchesSequence = ((JToken)inputObject["AlbumMatches"]);
                if (albumMatchesSequence != null && albumMatchesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken albumMatchesValue in ((JArray)albumMatchesSequence))
                    {
                        SearchResult searchResult = new SearchResult();
                        searchResult.DeserializeJson(albumMatchesValue);
                        this.AlbumMatches.Add(searchResult);
                    }
                }
                JToken mediaMatchesSequence = ((JToken)inputObject["MediaMatches"]);
                if (mediaMatchesSequence != null && mediaMatchesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken mediaMatchesValue in ((JArray)mediaMatchesSequence))
                    {
                        SearchResult searchResult2 = new SearchResult();
                        searchResult2.DeserializeJson(mediaMatchesValue);
                        this.MediaMatches.Add(searchResult2);
                    }
                }
                JToken timelineMatchesSequence = ((JToken)inputObject["TimelineMatches"]);
                if (timelineMatchesSequence != null && timelineMatchesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken timelineMatchesValue in ((JArray)timelineMatchesSequence))
                    {
                        SearchResult searchResult3 = new SearchResult();
                        searchResult3.DeserializeJson(timelineMatchesValue);
                        this.TimelineMatches.Add(searchResult3);
                    }
                }
            }
        }
    }
}
