// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Rg.ClientApp.Models
{
    public partial class SetImage
    {
        private int? _mediaId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? MediaId
        {
            get { return this._mediaId; }
            set { this._mediaId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SetImage class.
        /// </summary>
        public SetImage()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type SetImage
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.MediaId != null)
            {
                outputObject["MediaId"] = this.MediaId.Value;
            }
            return outputObject;
        }
    }
}
