// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using Rg.ClientApp.Models;

namespace Rg.ClientApp.Models
{
    public static partial class TimelineEntryDetailsCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<TimelineEntryDetails> DeserializeJson(JToken inputObject)
        {
            IList<TimelineEntryDetails> deserializedObject = new List<TimelineEntryDetails>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                TimelineEntryDetails timelineEntryDetails = new TimelineEntryDetails();
                timelineEntryDetails.DeserializeJson(iListValue);
                deserializedObject.Add(timelineEntryDetails);
            }
            return deserializedObject;
        }
    }
}
