// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Rg.ClientApp.Models
{
    public partial class UserSettings
    {
        private bool? _emailWhenMentioned;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? EmailWhenMentioned
        {
            get { return this._emailWhenMentioned; }
            set { this._emailWhenMentioned = value; }
        }
        
        private bool? _notifyWhenMentioned;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? NotifyWhenMentioned
        {
            get { return this._notifyWhenMentioned; }
            set { this._notifyWhenMentioned = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the UserSettings class.
        /// </summary>
        public UserSettings()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken emailWhenMentionedValue = inputObject["EmailWhenMentioned"];
                if (emailWhenMentionedValue != null && emailWhenMentionedValue.Type != JTokenType.Null)
                {
                    this.EmailWhenMentioned = ((bool)emailWhenMentionedValue);
                }
                JToken notifyWhenMentionedValue = inputObject["NotifyWhenMentioned"];
                if (notifyWhenMentionedValue != null && notifyWhenMentionedValue.Type != JTokenType.Null)
                {
                    this.NotifyWhenMentioned = ((bool)notifyWhenMentionedValue);
                }
            }
        }
    }
}
