// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Rg.ClientApp.Models;

namespace Rg.ClientApp
{
    public partial interface IComment
    {
        /// <param name='commentId'>
        /// Required.
        /// </param>
        /// <param name='likeRequest'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PostLikeByCommentidAndLikerequestWithOperationResponseAsync(int commentId, LikeRequest likeRequest, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
