// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Microsoft.Rest;
using Rg.ClientApp;

namespace Rg.ClientApp
{
    public partial interface IRgApiJenya : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        IAlbums Albums
        {
            get; 
        }
        
        IComment Comment
        {
            get; 
        }
        
        IInvitations Invitations
        {
            get; 
        }
        
        IMedia Media
        {
            get; 
        }
        
        INotification Notification
        {
            get; 
        }
        
        IProfile Profile
        {
            get; 
        }
        
        ISearch Search
        {
            get; 
        }
        
        ITest Test
        {
            get; 
        }
        
        ITimeline Timeline
        {
            get; 
        }
        
        IUploadMedia UploadMedia
        {
            get; 
        }
        
        IUserImages UserImages
        {
            get; 
        }
    }
}
