// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Rg.ClientApp.Models;

namespace Rg.ClientApp
{
    public partial interface IUserImages
    {
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='extension'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetByIdAndExtensionWithOperationResponseAsync(int id, string extension, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='mediaId'>
        /// Required.
        /// </param>
        /// <param name='extension'>
        /// Required.
        /// </param>
        /// <param name='commentRequest'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PostCommentByMediaidAndExtensionAndCommentrequestWithOperationResponseAsync(int mediaId, string extension, CommentRequest commentRequest, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='extension'>
        /// Required.
        /// </param>
        /// <param name='likeRequest'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PostLikeByIdAndExtensionAndLikerequestWithOperationResponseAsync(int id, string extension, LikeRequest likeRequest, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
