// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Rg.ClientApp;
using Rg.ClientApp.Models;

namespace Rg.ClientApp
{
    public static partial class NotificationExtensions
    {
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.INotification.
        /// </param>
        /// <param name='registration'>
        /// Required.
        /// </param>
        public static object PostByRegistration(this INotification operations, NotificationRegistration registration)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((INotification)s).PostByRegistrationAsync(registration);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.INotification.
        /// </param>
        /// <param name='registration'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostByRegistrationAsync(this INotification operations, NotificationRegistration registration, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostByRegistrationWithOperationResponseAsync(registration, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
