// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Rg.ClientApp;
using Rg.ClientApp.Models;

namespace Rg.ClientApp
{
    public static partial class ProfileExtensions
    {
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        public static UserSettings GetAsync(this IProfile operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IProfile)s).GetAsyncAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<UserSettings> GetAsyncAsync(this IProfile operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Rg.ClientApp.Models.UserSettings> result = await operations.GetAsyncWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        public static object PostAvatarByRequest(this IProfile operations, SetImage request)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IProfile)s).PostAvatarByRequestAsync(request);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostAvatarByRequestAsync(this IProfile operations, SetImage request, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostAvatarByRequestWithOperationResponseAsync(request, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        public static object PostBannerByRequest(this IProfile operations, SetImage request)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IProfile)s).PostBannerByRequestAsync(request);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostBannerByRequestAsync(this IProfile operations, SetImage request, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostBannerByRequestWithOperationResponseAsync(request, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='setting'>
        /// Required.
        /// </param>
        public static object PostMentionEmailNotificationsBySetting(this IProfile operations, OptionSettings setting)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IProfile)s).PostMentionEmailNotificationsBySettingAsync(setting);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='setting'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostMentionEmailNotificationsBySettingAsync(this IProfile operations, OptionSettings setting, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostMentionEmailNotificationsBySettingWithOperationResponseAsync(setting, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='setting'>
        /// Required.
        /// </param>
        public static object PostMentionPushNotificationsBySetting(this IProfile operations, OptionSettings setting)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IProfile)s).PostMentionPushNotificationsBySettingAsync(setting);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='setting'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostMentionPushNotificationsBySettingAsync(this IProfile operations, OptionSettings setting, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostMentionPushNotificationsBySettingWithOperationResponseAsync(setting, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        public static UserSettings PostValidate(this IProfile operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IProfile)s).PostValidateAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IProfile.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<UserSettings> PostValidateAsync(this IProfile operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Rg.ClientApp.Models.UserSettings> result = await operations.PostValidateWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
