// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Rg.ClientApp;
using Rg.ClientApp.Models;

namespace Rg.ClientApp
{
    public static partial class UploadMediaExtensions
    {
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IUploadMedia.
        /// </param>
        public static MediaUploadResults PostAsync(this IUploadMedia operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IUploadMedia)s).PostAsyncAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Rg.ClientApp.IUploadMedia.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<MediaUploadResults> PostAsyncAsync(this IUploadMedia operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Rg.ClientApp.Models.MediaUploadResults> result = await operations.PostAsyncWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
